version: '3.8'

services:
  backend:
    build: ./BACKEND
    ports:
      - "5000:5000"
    volumes:
      - ./BACKEND:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./FRONTEND
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules
    depends_on:
      - backend